### PR TITLE
Round static scale

### PR DESCRIPTION
**Pull request by TrajansRow**
This should avoid plaid static...

### CODE REVIEW

**Comment by Hopper262** [comment]
The plaid doesn't bother me (I kinda like the visual variety when it's messy), but this does give consistent squares as promised. I'll leave it for @treellama to decide.

**Comment by TrajansRow** [comment]
I hope I didn't kick a hornets next proposing this [seemingly minor] shader enhancement. The effect is surprisingly hard to get right (I don't think I've seen anything quite like this in any other game), but it's at least a fun problem to work on.

Oh, and if you want to make the plaid effect even messier, try adding in those two "time*10.0" coordinate translations that the bloom variant has.

**Comment by Hopper262** [comment]
I've had fun and learned a good bit too; I appreciate you heading down this road. Sometimes things need a good kicking to shake the dust off, and see if they're still in working order. ;)  I hope the discussion hasn't sucked all the fun out of it for you!

**Comment by treellama** [comment]
It's hip to be square! I think that's more faithful to the original.

I also like the bloom in squares instead of bands. Try 2.0/2.0 at 0.5 probability, and see what you think? Looks good to me at 1080p. Bloom behavior is way more subjective, though. I can always write a S7 plugin if we decide to go with the horizontal bands. I might add the uniforms though.

**Comment by Hopper262** [comment]
Bloom is subjective and I've liked all the different attempts, but the squares do feel more in keeping with the original. I'm kinda digging 2.0/2.0/0.8, which lets more of the fine detail through.

**Comment by treellama** [comment]
2.0/2.0/0.8 is good too

**Pull request merged**
