### PR TITLE
Scale static effect based on screen size and resolution.

### PR DESCRIPTION
**Pull request by TrajansRow**
Addresses scale concerns in #135

### CODE REVIEW

**Comment by TrajansRow** [comment]
My intention is to make the static effect look more like the original game. This change attempts to make the static 'pixels' 1/480th of the logical screen height (approximating the appearance of a 640x480 display).

**Comment by Hopper262** [comment]
Actually, the logical height of the original game would be 320 pixels, not 480. The portion reserved for the HUD is not part of the 3D view and is not reported in the uniforms.

**Comment by TrajansRow** [comment]
What I’m trying to do is approximate the size of a single pixel from a 640 X 480 display, if it were a scaled to arbitrary dimensions (not necessarily correlating with the original HUD proportions).

Hopefully it looks better at more resolutions now.

**Comment by treellama** [comment]
This is getting much closer! At 640x480, I see a kind of a plaid of rectangles and L's:

WhatAboutBob_0010

Compare to the software renderer:

WhatAboutBob_0011

And the Aleph One 1.2 shader:

WhatAboutBob_0012

**Comment by Hopper262** [comment]
With the floating HUD, the logical size passed to the shader is 640x400. This creates a block size of 0.83px (this PR: 400.0/480.0) or 1.25px (current master: 400.0/320.0), so I'd expect some aliasing artifacts.

Personally, I like this scaling better than fixed-pixel-size static. Now that the blocks stay at constant angular size regardless of window size, like the weapons in hand and all other elements of the 3D view, it feels more like a part of the world to me.

**Pull request merged**
