### PR TITLE
Fix memory leak

### PR DESCRIPTION
**Pull request by Kolfering**
Hello

### CODE REVIEW

**Comment by treellama** [comment]
Where is this leaking? allocate_shading_tables is only called from load_collection, and presumably unload_collection is called in balance with load_collection

**Comment by Kolfering** [comment]
TBH I didn't really dig into that to much to understand why, but everything is not free correctly.
Here if I begin a new game and come back to the lobby.

image

**Comment by Kolfering** [comment]
Looks like this is because of load_shapes_patch where allocate shading table is also called and not free from there

image

**Comment by treellama** [comment]
Ah, maybe. I dislike combining shared_ptr with malloc/free--but C++11 doesn't support arrays in shared_ptr. What about just using a std::vector with resize() and data()?

**Comment by Kolfering** [comment]
Sure

**Comment by treellama** [comment]
Thanks! This will not actually release the memory, of course, but it won't leak it. Good enough for our purposes.

**Pull request merged**
