### PR TITLE
Update player.cpp

### PR DESCRIPTION
**Pull request by ObsidianCarnageX12**
Removes the end level teleportation delay for Marathon 1.

### CODE REVIEW

**Comment by treellama** [comment]
Why would a Marathon shapes file alter the teleportation delay on a terminal?

**Comment by ObsidianCarnageX12** [comment]
It is using the shapes file to check if it is in fact M1. If that is true then it sets the delay to 0.

**Comment by treellama** [comment]
What if you're running Marathon 2 shapes with a Marathon map? The teleport delay may be tied either to Marathon physics, or map, but definitely not shapes. Or perhaps it's MML?

Can you describe in detail what you are trying to fix?

**Comment by ObsidianCarnageX12** [comment]
Can you elaborate as to why someone would want to do that , instead of using M1A1 ? It already would not work if you tried to use Marathon 2 shapes in a M1 map.

**Comment by ObsidianCarnageX12** [comment]
In Detail : Current A1 has a short delay between terminal exit and level transition . This did not exist in vanilla Marathon.

This code removes said delay.

**Comment by tbcr** [comment]
> Can you elaborate as to why someone would want to do that , instead of using M1A1 ? It already would not work if you tried to use Marathon 2 shapes in a M1 map.

Yeah, doing M2 shapes using M1 maps seems like a corner case for people who are bored out of their minds. Case in point, AlbertHamik using a Wheels shapes file and using M2 map file. 

Yes, Marathon Infinity can run M2 shapes and Map, but M1 stuff is already kinda hacky to begin with since you're essentially forcing the M2 engine to behave like M1.

**Comment by tbcr** [comment]
[This part for some reason got cut off of my previous response.]

Essentially, Obsidian is just wanting to ensure that there is little behavioral differences between Macintosh M1 and A1 M1.

If there is a better location in the code to implement the changes offered, it would benefit to know.

**Comment by treellama** [comment]
My example was just an illustration of the point: shapes and teleportation delays have nothing to do with each other. The teleport delay is initiated by terminals, so perhaps it should be coupled with the M1 map instead of shapes.

It's only a half second, by the way--hardly noticeable.

**Comment by treellama** [comment]
I think using the group flags "group_is_marathon_1" to remove the delay from `teleport_to_level` in computer_interface.cpp would be a better way to do this. Since it only applies to original Marathon terminals.

Let me know what you think about that approach.

**Comment by ObsidianCarnageX12** [comment]
That approach sounds better yes , I just did not see said flag in the code during my initial combing.

**Comment by treellama** [comment]
If you want to submit an issue I can fix it, or you can resubmit a pull request, your call!

**Comment by ObsidianCarnageX12** [comment]
I have asked TBCR to build this implementation as I do not have a linux box one hand for testing atm.

**Comment by ObsidianCarnageX12** [comment]
Most recent pull request should be good to implement now. Thank you

**Comment by treellama** [comment]
As submitted, since the flag is a constant, this will always remove the delay. I'm opening an issue to fix it myself :)

**Comment by treellama** [comment]
See #195

**Comment by tbcr** [comment]
I think I might know what is going. I think it's how they setup the check. Lemme take a look into it.

**Comment by ObsidianCarnageX12** [comment]
Close this pull request , I will have to do some more stuff to it and dont want to flood your email/notifications

**Pull request closed without merging**
