### PR TITLE
Improve mouse delta calculations (pre-action flags)

### PR DESCRIPTION
**Pull request by LidMop**
These commits clean up and make corrections to calculations that govern the input yaw and pitch values _before_ they get encoded into action flags (consequently, there is no compatibility impact).
- Mouse velocity is no longer used (and wasn't being calculated accurately anyway). Yaw/pitch is now proportional to mouse delta (when mouse acceleration is off), scaled such that there is no perceived difference under normal framerate. The effect is that the mouse sensitivity perceived by the player is now framerate-independent, and the mouse handles better under periods of unstable framerate.
- X/Y mouse delta limits in a single frame are almost doubled, up to implementation limits imposed by action flags. This makes it easier to make very hard, rapid turns with the mouse (up to about 44.3° yaw-wise in a single frame, up from 22.5°).
- Vestigial remnants of a bizarre "mouse-controlled player velocity" feature have been removed. This feature makes the player go forward/backward in proportion to mouse Y velocity, but it has not been fully implemented since the M2 source release: 1) it doesn't have a Preferences checkbox; 2) it can't reach maximum forward speed due to incomplete/inappropriate calculations; and 3) it is completely impractical unless you're using a trackball, because you have to keep moving the mouse forward to go forward and looking up/down can only be done with the keyboard. (As a side note, I vaguely remember using this feature (and not liking it much, mainly due to the lower forward speed) in M1 or maybe just the M1 demo... is my memory faulty? Was this implemented in M1?).

### CODE REVIEW

**Comment by LidMop** [comment]
I would like to add that mouse acceleration is not being calculated correctly at the moment, because the squaring only happens every 33 ms (on average), whereas raw mouse deltas are accumulated every 16 ms (on average). This makes the result too high, e.g. (2 + 3)^2 > 2^2 + 3^2. Either mouse acceleration should be dropped or the squaring should happen at the same time the raw mouse delta is obtained from SDL. I wasn't sure how to handle this issue so I left it alone in these commits.

**Comment by Hopper262** [comment]
I'll consider these as I continue my own overhaul of the mouse code.

**Comment by LidMop** [comment]
Are you looking into increasing the precision of player orientation throughout the engine so that players can make super-fine aiming adjustments? That's been on my wish-list for the longest time. I understand that it would break compatibility and require extensive code changes. If you're not planning to do that, I'll happily look into it.

**Comment by Hopper262** [comment]
I think it's more that increased precision would break compatibility **OR** require extensive code changes. If you don't care about compatibility, you can probably increase angular bits in world.h, convert facing and angular acceleration values read in from the map and physics, and be a good way along.

It's not on my own to-do list, so feel free to give it a go; it could be a really fun project. Maybe you'll even find out it's not as hard as we all thought.

**Comment by Hopper262** [comment]
Hey, I found out where the mouse-moving-forward code came from. Pathways into Darkness had optional mouse controls, for turning left and right, and moving forward and backward. There was no looking up and down in that engine, but I guess Bungie felt they couldn't let those extra mouse directions go unused!

**Comment by SolraBizna** [comment]
Changing `ANGULAR_BITS` would automatically propagate to _most_ code. Some code, scattered around the engine, is hardcoded to assume 9-bit angles. Other code is "tuned" in such a way that it happens to work out as intended with 9-bit angles. Naturally, this would murder compatibility.

It might be possible to turn `ANGULAR_BITS` into a variable instead of a compile-time constant without murdering performance on a modern machine... the only likely casualty would be my dream of playing Aleph One on an EOMA68 laptop....

**Comment by LidMop** [comment]
+1 for the PiD history note!

I'm neck neep in going through the codebase to see how best to increase the precision. Changing `ANGULAR_BITS` (and updating all code that assumes 9-bit angles, including initializations from physics/map files) is certainly one way, and it's what I'm leaning towards so far. Another strategy I'm looking at is to upgrade only the subset of code that actually needs higher precision: this would involve changing the representation (and possibly size) of a few key data members and overhauling nearly all code that references them.

Independent of those strategies, I'll need to update the encoding of angle deltas in action flags to take advantage of the higher precision without sacrificing the min/max delta limits. I think I can do that without requiring more bits by using a non-linear distribution of values clustered around 0 (kind of like floating-point values). The alternative would be to increase the size of action flags (ouch!).

As for compatibility, wouldn't it be impossible to achieve in network games? If player A fires a bullet on a precise trajectory that can't be represented by player B's engine, there's no way to recover from that, right?

**Comment by Hopper262** [comment]
The network handshake includes version checks. Aleph One has changed gameplay at various times in the past and incremented the version; player B wouldn't be able to join player A's game or vice versa. Films also have a version number near the start of the file. (Interestingly, Bungie never filled it out, but Aleph One started using it a few years ago.)

These versioning mechanisms mean it's possible to make gameplay-affecting changes, or even changing the network protocol or film format. For replays you still have to support the old formats and mechanics, so breaking compatibility means more code to write and maintain, but some features are worth the burden.

**Comment by treellama** [comment]
This change (and the mis-applied fix to #45 ) makes the mouse code much worse here. Very un-Marathon-like. I'm OK with removing vestigial code, but please consider reverting the delta limits to where they belong.

**Comment by LidMop** [comment]
treellama, in what way are the original limits desirable? Is it just that we want to maintain the de facto gameplay difficulty that arises from the max turn rate?

Also, just to be clear, is it only the limits you want reverted, or do you see other problems with this pull request?

**Comment by treellama** [comment]
A primary focus of this project is to maintain the original gameplay, and mouse control is a fundamental part of the original gameplay. I wouldn't choose "difficulty" as the word to describe it, but rather "feel". In particular, adjusting the turn limits has the potential to alter the mouse/keyboard balance in net games which has been working well for decades.

The other changes in this request seem OK but I haven't considered them deeply. It's not obvious where the 66.0f comes from without reading the commit message, but then again the reader may not understand why there is a divide by 2 in the Bungie code. Note that you preserve the bug with the ill-considered "mouse_acceleration" preference where disabling it removes the *.4f that offsets said divide by 2. But that's an issue for #45 ; removing the preference, restoring the nonlinearity along with the *4.f would mean that 66.f is the correct sensitivity divisor.

**Comment by SolraBizna** [comment]
Raising the limits does kinda screw those of us who try to play with the keyboard. Not that we were that well off to begin with.

Preserving original behavior for those who want it is important, but if the mouse input and game loop are having a duel across time and space whose outcome randomly affects the mapping between mouse input and aiming, we can all agree that's bad, right?

I'd guess that the original code running on Classic MacOS was at worst merely framerate dependent, and not also dependent on the whims of an event thread, but I have nothing to back that up. (My knowledge of the workings of ADB mice stops where the driver ends and Event Manager begins.) If so, removing the effect of thread scheduling on the inputs would then be a restoration to the classic experience. And removing the framerate dependence, so long as it preserves the 30fps experience, makes things more consistent for everyone. Win?

**Comment by LidMop** [comment]
I firmly dislike the fact that moving the mouse too far within a single frame causes some of that movement to be ignored, whereas if the exact same mouse movement (same duration, same distance) happened to be sampled evenly across 2 frames, it would all count. That's inconsistent mouse handling. On the other hand, I now agree that the original turn-rate limits are part of the gameplay and should not be changed (by default, at least).

I have an idea:

1. Add state, _desired yaw_ and _desired pitch_, that track the yaw and pitch as if there were no turn-rate limits.
2. Take the difference between these variables and the current player yaw/pitch, clamp the differences to the turn-rate limits, and feed the results to action flags instead of the (clamped) mouse deltas directly.

This way, moving the mouse very quickly results in a turn that executes over multiple frames. I'll try this out and see if it's better.

**Comment by treellama** [comment]
At such a low input rate, I worry it could feel boaty. Can't hurt to try it I guess. Although, I think I may depend on the turn-rate limit when aiming! I just throw the mouse in the direction I want and down, and at the right time (muscle memory?) click the button to fire a missile at the floor. So there's still a chance of throwing off that "feel". Keyboarders totally play this way, so I think it's fair to argue that the feel of the mouse input be preserved as well.

Drifting off topic: the latency hiding code could benefit from something like this as well. Currently, if action flags must be made up for a player because they are received late, as a client there is noticeable jitter trying to fight the made-up flags the server is sending to get the pitch/yaw back to the place the player wants to aim. At the moment the server zeros out the pitch/yaw when making up missing flags, which might also not be the right behavior.

(Ironically, having the ability to pitch/yaw faster would allow the client to hide latency better, by restoring the desired pitch/yaw over fewer frames! But at the cost of messing with the unintentionally balanced turn rate limits in the original, which I don't think is worth paying)

Aleph One's input and networking code are a 20-year series of hacks on top of hacks, with every contributor thinking he can do better. Welcome to that group!

**Comment by SolraBizna** [comment]
> At such a low input rate, I worry it could feel boaty. Can't hurt to try it I guess.

Regardless of the rate at which inputs are being read, they only take effect when a tick ticks. As long as they're read at least that often, it should be fine.

> I just throw the mouse in the direction I want and down, and at the right time (muscle memory?) click the button to fire a missile at the floor.

This kind of thing is exactly why, whatever improvements are made, we need to at least keep the option to preserve the classic feel. 20+ years of muscle memory dies hard (and doesn't drop ammo).

**Comment by LidMop** [comment]
Oh wow, my experimental idea was a cure way worse than the disease. Mouse felt like a mattress. Made of Jell-O. I now think that any kind of (de facto) simulated mouse input beyond the immediate frame is bad.

I again compared the original and current (higher) delta limits by having the the higher limits be active while the microphone key is down, and the original limits be active otherwise. The higher limits give a **noticable improvement** in mouse feel when making quick turns. Unfortunately, this is directly at odds with maintaing the original parameters of gameplay, so I am (reluctantly) in favor of **reverting** to the original limits.

Out of curiosity, I furthermore compared the higher limits against **no** limits (using global variables to bypass action flags), and I couldn't tell the difference. This is because few of my mouse deltas exceeded the limits anyway, or if they did, then not by much. In other words, higher limits have diminishing benefits.

**Comment by treellama** [comment]
> I again compared the original and current (higher) delta limits by having the the higher limits be active while the microphone key is down, and the original limits be active otherwise. The higher limits give a noticable improvement in mouse feel when making quick turns. Unfortunately, this is directly at odds with maintaing the original parameters of gameplay, so I am (reluctantly) in favor of reverting to the original limits.

It's tough. Newer games let you turn _as fast as you want_, and if Aleph One doesn't do that, it will turn off players used to new first person shooters. But if it does, then it won't be quite as faithful to Marathon 2. Since we only have one "source port", if we stray too far from that faithfulness then there is _no_ way to play the originals true to form without an emulator.

With software renderer becoming more and more difficult to support, and new players clamoring for modern mouse look, it feels like we need another source port--but, given the age of the networking, input, and rendering code, it seems pointless to base anything on the Marathon source code. A port of the engine's assets and physics to a modern engine would make much more sense.

So I keep coming back to keeping Aleph One faithful to the originals, and hoping somebody does find a way to do a faithful-but-updated recreation in a newer engine. But, I too regret being held back sometimes :)

**Comment by Hopper262** [comment]
Since there is no readily available alternative to Aleph One, I feel it's vitally important we do all we can to have our cake and eat it too. The gaming landscape is a big pond and we have few opportunities to draw in the future fans who will build that ecosystem of alternatives.

Commit ed52955 adds a mouse max-speed slider. 50% limits the mouse to the speed before this pull request, and is applied when importing older preferences files. 100% allows the full representable speed, and is the default for fresh installations.

Side note: in the future, I want to add a first-run choice of "classic" vs. "modern" preferences. It's much harder than it should be to get Aleph One configured to an emulation-like state, and a visible choice will make it easier for everyone to get the experience they want.

**Comment by treellama** [comment]
The slider is even worse than the original patch! It still disadvantages keyboarders in net games (because what competitive player will leave it set to 50%!?) but now there's _another_ slider.

**Comment by Hopper262** [comment]
Yes, when virtually anyone who's played a mouse-driven FPS leaves the game in disgust, keyboarders _do_ have less of a disadvantage. I agree on that point.

**Comment by SolraBizna** [comment]
I wonder how many keyboard netplayers are left. I don't count, since I don't play competitively at all anymore. And we almost certainly aren't getting any new ones...

I've racked my brains over this, and I haven't thought of a way to handle this where everyone wins. Keep the limits where they are, and the 360-noscope generation† will feel like they've got a brick on their mouse. Raise them wholesale, and the keyboarders' tiny sliver of a chance against mousers becomes even tinier. Make a checkbox/slider, and we've taken another step towards becoming a Christmas tree. Make the limits MML-controlled, and we cause the creation of another plugin about which players will violently disagree between "must-have" or "must-disable"... and therefore create another reason for netgames and films to "randomly" desync...

Sigh.

† "360-noscope generation" here defined as "anyone born after me" ;)

**Comment by treellama** [comment]
This isn't a mouse issue. How quickly the player can turn is a physics issue. Change it if you feel it's necessary, but don't make it a preference. Core game physics isn't a user preference.

**Comment by SolraBizna** [comment]
Wait... this doesn't change keyboard turning speeds too, does it?

**Comment by LidMop** [comment]
No, just mouse control. Keyboard turning uses constants loaded from the physics model data. Amusingly, this means that you can turn faster with the keyboard than the mouse if you use a custom physics model.

**Pull request merged**
