### PR TITLE
Add a system for making Lua netscripts and solo scripts configurable.

### PR DESCRIPTION
**Pull request by SolraBizna**
This PR makes it possible for netscripts and solo scripts to have dialogs like this:

A "script options" dialog containing six checkboxes and a selection widget.

This system is designed to have the minimum possible interaction with the rest of the system. Three buttons have been added to other dialogs (to open this one), and those buttons are disabled unless you enable a script that has configuration support. Changed configuration values are written back into the script (with great care). As far as any other part of the game is concerned, a "configured" Lua script is no different from any other self-contained Lua script. Thus, network compatibility is assured, and there is no associated data hanging out elsewhere in the environment.

The syntax for the configuration dialog specification is deliberately very simple and very strict. The above dialog, taken from [A1mega](https://github.com/SolraBizna/a1mega), is implemented by having the following at the top of the script:

```lua
--! configuration 1.0
--! toggle enable_port "Allow Teleporting to Teammates"
local enable_port = false
--! toggle enable_navi "Announce Mission Completion"
local enable_navi = true
--! toggle enable_iff "Disable Friendly Fire"
local enable_iff = false
--! toggle enable_aw "Enhance Automatic Weapons"
local enable_aw = true
--! toggle enable_shld "Halo-Style Shields"
local enable_shld = true
--! toggle enable_hardcore "Hardcore Co-op Mode"
local enable_hardcore = true
--! select inventory_mode "Inventory Mode" "Normal" "Shared" "Fisto!"
local inventory_mode = 3
--! end configuration
```

If anything goes wrong during parsing, or anything looks questionable, the configuration dialog will print a (hopefully) friendly error message and refuse to do anything. In case anything goes wrong during saving, the original script is kept around until almost the last possible moment. Details of the format are documented in `Lua.html`/`Lua.xml`.

I believe the current implementation is complete and future-proof. ~~The only problem that I'm aware of is that **I have not added the new source file to the XCode project**. (Visual Studio and Automake have been made aware of the new file.)~~

### CODE REVIEW

**Comment by SolraBizna** [comment]
I have added it to the XCode project and now it builds on all three platforms that exist.

**Comment by SolraBizna** [comment]
Per discussion at the time on the Discord server, this feature will not be merged in its current state. Fragility of film playback was a particular concern.

**Comment by treellama** [comment]
We had also, in a private thread, discussed ways to improve/merge this. I think the big thing blocking this is code to transfer the settings over the network. No ETA on that

**Comment by SolraBizna** [comment]
Unless I'm misunderstanding, there's no need for special support for transferring the settings over the network. They are embedded in the script, so they will be sent when the script is sent. Though if this were extended to include configuration of scripts in plugins, that *would* become a problem.

**Pull request closed without merging**
