### PR TITLE
Smoother mouselook

### PR DESCRIPTION
**Pull request by TrajansRow**
Permits apparent mouselook to exceed frogblast precision.

### CODE REVIEW

**Comment by TrajansRow** [comment]
This effect is least noticeable when acceleration is disabled and sensitivity is high. I attribute this to the SDL mouse position being truncated to int

**Comment by TrajansRow** [comment]
Does it make sense having the preference for this under rendering options? Technically it is a renderer effect, but users might expect mouselook related things to be under controls.

**Comment by LidMop** [comment]
Oh wow, I just noticed that this PR improves mouselook independently of the option because you're [unconditionally maintaining](https://github.com/Aleph-One-Marathon/alephone/pull/117/files#diff-bdc15fc7ce866ccbc4a79c69eefb2063R152) any fraction of the delta that was not used on the previous tick. In other words, without this PR, you can move the mouse an arbitrary distance without turning the player if you move it too slowly. This PR correctly accumulates that motion. I hadn't even realized that was an issue. Thank you for fixing that!

Regarding where to put the option, I'd put it in the Aim tab, since it does affect (the feel of) mouselook.

**Comment by Hopper262** [comment]
The "moving the mouse too slowly to turn" problem was a relatively recent introduction (1a9888a), one @LidMop actually argued against and then forgot about. ;)  It's reverted in 7029935, because I've had some reports of mouse regressions. For the near future, I want to keep 1.2-style mouse handling as an option, so users can compare against 1.2 and separate SDL bugs from mouse-feel options. We may fully switch to this PR's strategy in the future, but for now it should be tied to the preference.

Anyway, this is an interesting and cool addition that can help us move toward fully removing our angle limitations. Considering that future direction, I see some room for improvement:

* Instead of collecting lost yaw/pitch directly in the renderer, it would be better to collect these values into new fields of the `world_view` variable in `render_screen()`. This makes the data and preference (theoretically) renderer-independent, as it would be consistently delivered without renderers needing to call over to mouse code.
* Some corner cases are ignored in the current PR, such as a player spectating another through Lua. `render_screen()` is a better place to track and consolidate these conditions than `mouse_idle()`.
* This lays the groundwork for reworking the `view_data` structure for a higher resolution. Aside from the special case of `explore_view`, it does not affect gameplay or film playback, so we could use higher-resolution angles throughout the render code without breaking functionality.
* Between this PR and the existing code from 731de52, `mouse_idle()` winds up anticipating and duplicating a lot of what `mask_in_absolute_positioning_information()` is going to do. The mouse code passes high-precision information to the latter function, so it seems logical for the masking function to be the one to calculate and store the discarded remainders. As a bonus, we'd get this smoothing for free in game-controller mode too.

**Comment by Hopper262** [comment]
I've accepted this into the `mouse-improvements` branch, to get it integrated with some refactoring LidMop and I have planned. If you're interested in working on any of the additional enhancements mentioned above, let us know. Either way, thanks much for your efforts, and I'm excited to get this feature into the next release!

**Comment by TrajansRow** [comment]
I would like to implement the restructuring that you suggested; it’s definitely an improved design. It is unfortunately complicated by my desire to support single-precision floating point input. SDL obviously does not do that yet; but it will need to eventually. I might just need to do a little re-plumbing.

**Pull request closed without merging**
