### PR TITLE
Blockier static

### PR DESCRIPTION
**Pull request by TrajansRow**
The static effect is looking more like a grey haze. What do folks think about this adjustment?

static

### CODE REVIEW

**Comment by treellama** [comment]
I really like the look. Does it work well at lower resolutions?

I think static effects should glow (bloom), but we couldn't get it working with the authentic static shader (it would just blur the whole thing). Blockier static might be able to glow :)

If we don't include this as the default, I encourage you to release it as a plugin!

An aside: I appreciate that you use spaces instead of tabs, so you're not a monster. But you use three spaces to indent!? So you're sort of a monster. Of course, the current code base is wildly inconsistent. Maybe we should draft a style guide :)

**Comment by TrajansRow** [comment]
Here’s two screenshots; one at 640x480 and the other at my native res (both high ppi). Obviously the first is much chunkier, but still pretty good in my opinion. I could try to scale the effect based on the color attachment size, but I would probably need to add another uniform for that. My inclination is to just consider it good enough. If necessary, I could add in a little high frequency noise to break it up.

Also, it looks pretty good with bloom using nearly duplicated code from the main shader.

640x480
3360 x 2100

**Comment by Hopper262** [comment]
The blockiness definitely helps with high-PPI monitors, and the bloom effect is terrific. Great job!

**Comment by treellama** [comment]
This is good looking but wayyy to blocky at 1080p, and wayyy wayyy too blocky at 640x480 (there's like 6 blocks total when a BoB teleports out). Additionally, this leaves no way to get the original effect for purists...could we move this to a plugin that we include with the default data files?

**Comment by ravenshining** [comment]
It looks fine for me at 1200p... usually.  But, sometimes it just goes completely white, and that looks really bad; other times, the pattern is much too obvious; and all the time, there's just too much white.  And while I enjoy having it, I agree that being unable to turn it off is a problem, as it looks more like Star Trek than the original static effect.

**Comment by Hopper262** [comment]
I'll move it to a plugin.

**Comment by TrajansRow** [comment]
Can anyone provide a screenshot of when it goes completely white? It should definitely not do that.

I think moving this to a plug-in is fine, but would you be open to adding another uniform that provides the screen resolution and/or scale? The whole point of this change was to make the effect look more like the original game.  I just picked an arbitrary scale, but obviously one size does not fit all in this case.

**Comment by treellama** [comment]
I think passing in a screen resolution/scale uniform would be fine. The closer it looks to the original (with bloom disabled, 640x480 as a reference) the less I think this would need to be a plugin. I didn't realize that was the intent when I suggested moving it :)

**Comment by treellama** [comment]
I don't see it go completely white, but there are bands of colors that pulse up and down. This is only when bloom is on, so IMO it's not a big deal.

WhatAboutBob_0002

The colors look different to me than the original:

WhatAboutBob_0004

But that could just be the size of the blocks.

For what it's worth, the software renderer supports high resolution, and continues to render static at single pixel resolution.

WhatAboutBob_0005

I don't think we have to match that, since those higher resolutions were added later by Aleph One developers, not by Bungie. But it also looks OK to me (from having played with the classic OpenGL renderer all those years), so maybe we just need a HiDPI uniform? This is a judgement call--input (as well as all your hard work hitherto) is very appreciated.

**Comment by ravenshining** [comment]
For teleporting monsters and dying S'pht, it's mostly okay, if a bit bright and overly patterned.  It's when you have something that isn't transient that it really goes wrong, like an invincibility powerup, your weapon after having picked up an invincibility powerup, the obscure case where a third-party scenario uses a texture with the static transfer mode, and when a Lua script such as Vasara uses static to highlight something.

Here we have a SPNKR gone completely white in proper Marathon 1.  It stayed like that for a good 10 seconds, before slowly lightening with a very noticeable and unchanging banding pattern:

Tryagain_0003

While looking for screenshots, I also noticed that the bloom doesn't stay constant - it might start out with bloom, and then after a while the bloom goes away for a minute or so, and comes back later.  Such is the case here, by the time I cleared out the Deprivation Chamber the powerup stopped blooming:

NeverBurnMoney_0001

After a few seconds, the static breaks down and goes white:

NeverBurnMoney_0002

Then it starts glowing again, still mostly white:

NeverBurnMoney_0004

Here's a case of banding pattern in painful evidence, as well as a partial whiteout and failure to bloom:

CoolFusion_0006

Granted that is on a wall in a 3rd party map, but the wall helps to to illustrate how the banding pattern stays in the same spot on the screen when you look around:

CoolFusion_0007

**Comment by TrajansRow** [comment]
Thanks for the example TL. That’s actually what I expect bloom to look like, but as you say the static is way too blocky. I am working on a change that will scale that effect better based on the resolution. Also, I think the static colors will be pretty true to the original.

When bloom is turned on, it’s obviously going to brighten things somewhat. To compensate, the bloom shader randomly adds horizontal slices of black to the output. I did that in order to let more of the static colors come through without being blown out so much. If you want, I can turn off the horizontal bias; it was just a design choice on my part, but I’m not super attached to it.

**Comment by TrajansRow** [comment]
Wow; those are some great glitches! While I’m not totally sure what’s going on there, it looks like the GLSL randomizer is not working on your setup.

I actually replaced the randomizer in these new shaders with one that seem to be getting me better random numbers, but if it’s causing problems I can just revert that.

**Comment by ravenshining** [comment]
I don't really know what that means, but from some Yandexing it seems that some GPUs use different math for functions like this? I guess maybe my Quadro FX 1600 M, being a 12 year old business laptop GPU, might do things differently than a modern desktop gaming GPU.  Maybe that makes my machine a good thing to test stuff on for compatibility :-)

**Comment by Hopper262** [comment]
With the uniforms added in cd59d4f, create blocks of fixed visual size with:

```
vec2(gl_FragCoord.x * (logicalWidth / pixelWidth) / blockSize,
     gl_FragCoord.y * (logicalHeight / pixelHeight) / blockSize)
```

To create blocks which scale like the weapons in hand, use something like:
```
vec2(gl_FragCoord.x * (320.0 * (logicalWidth / logicalHeight) / pixelWidth) / blockSize,
     gl_FragCoord.y * (320.0 / pixelHeight) / blockSize)
```

Note that in the bloom shader, the pixel ratio may not match the logical ratio.

**Comment by TrajansRow** [comment]
Thanks, Hopper! That's more than I have in my branch, but it should do the job.

My greater concern is the problem ravenshining reported. I've pored over the Khronos docs, and every new function I've added has support back to GLSL 1.1 (with the exception of sign(), which was easy to replace anyway). My fear is that gl_FragCoord (which is essential to this effect) is not properly supported on some hardware. I'll try to submit another patch in the next couple of days... If It doesn't fix ravenshining's issue (which very likely would affect others too), this change will probably have to become a plugin anyway.

**Comment by Hopper262** [comment]
I have no qualms about requiring proper gl_FragCoord support. Directing these users to a plugin with the old shader is an acceptable solution. I have to imagine that users installing new software on 12-year-old computers have faced more awkward workarounds than installing a plugin.

**Comment by ravenshining** [comment]
According to Yandex my video card does support gl_FragCoord, and OpenGL 3.3.  So perhaps it's something else?

**Comment by Hopper262** [comment]
@ravenshining What OS and driver are you running? Are you using the most up-to-date release from Nvidia's site?

**Comment by ravenshining** [comment]
Debian 8+backports, using the official Nvidia drivers (not Nouveau).  I'm using the latest in the repositories, 340.106-1, but now that I check, Nvidia released a version 340.107 last summer.  It's... not trivial to use Nvidia's installer instead of apt, but I'll give it a shot.

**Comment by Hopper262** [comment]
@ravenshining Here's a simpler plugin to see if gl_FragCoord is working:

[FragCoord test.zip](https://github.com/Aleph-One-Marathon/alephone/files/2990463/FragCoord.test.zip)

 With git master and invincibility on, you should see a gradient effect like this:

NeCedeMalis_0012

**Comment by TrajansRow** [comment]
That’s a great idea for a test - I’m interested to see what comes out of it! 

For reference, new glsl functionality required for this change are mod(), fract(), sign(), floor(), and of course reading gl_FragCoord.

**Comment by Hopper262** [comment]
Thanks for breaking it down, I can put together tests on any of those until we find a smoking gun. I also remember testing one video card years ago that choked on shaders beyond a certain size; it could be each of the parts works, but it starts failing if the overall shader is too complex.

**Comment by ravenshining** [comment]
That worked just fine :-) I even played through to the end of this scenario while invincible to be sure, as I've noticed that often the static will look okay for the first few minutes of gameplay, and then slowly become less staticy and more stripey.  On the other hand, I haven't been able to detect a pattern to when it blows out to total white.

MissedIsland_0003
MissedIsland_0002

**Comment by TrajansRow** [comment]
I'm puzzled by what ravenshining is seeing... the FragCoords look good (no obvious corruption or banding).

There is a potential issue if tick_count gets too high due to a uint32->float conversion, but in my experiments it only causes static to stop animating (otherwise looking normal). What did the original shader-based static effect look like for you?

Also, I'm blown away that someone tried to recreate Myst island in AO.

**Comment by ravenshining** [comment]
The previous shader effect, before "blockier static"?  I thought it looked fine.   Not noticeably different from the software effect or the original thousands of colours effect

It seems my memory of a dark static with almost no white was based on playing the originals in 256 colour mode, so that may be colouring my "all the time there's too much white" comment - here's a screenshot:
marsneedswomen

Not that that excuses the whiteouts and banding.

That's an old map from the Map Making Contest of '97.  Unfortunately for Missed Island, the terminals don't render correctly in A1.  I've been meaning to file a bug report, but I want to gather more information and make sure my copy isn't corrupted or something as it crashes Basillisk II.

**Comment by TrajansRow** [comment]
I can’t quite put my finger on what it is, but something about that screenshot does not look right. Is that the older shader effect?

**Comment by treellama** [comment]
Hah, that's the original game! Super shield looks different in 256 colors vs thousands/millions.

**Comment by TrajansRow** [comment]
Wow; I have to say that doesn’t look great ( it also does not appear to be totally random),  but I don’t think I ever played it in 256 mode.  Does anybody have a screenshot of what 16 bit static looked like?

**Comment by treellama** [comment]
24-bit and 16-bit look close enough; it's only 8-bit that has to follow the palette. This screenshot was 24-bit:

**Comment by TrajansRow** [comment]
Ah ha! that looks more familiar. I’m also impressed with just how ok the 256 mode looked.

So, with a real example like this, am I correct in observing that there are only eight colors that comprise the static? The new shader effect randomizes the whole range of each channel...

**Comment by ravenshining** [comment]
Sure, here are all the statics in the same situation (with the last one behaving correctly for once):

marsneedswomen-all

**Comment by TrajansRow** [comment]
Thanks for the comparison! You can see the color differences between the software and the original shader implementation.

So, the blockier example is clearly not working on your rig. With bloom off, it should look almost identical to the old shader. Something isn't being calculated right, but I can't identify what it is.

**Comment by ravenshining** [comment]
With bloom off, it looks fine for the first five seconds after a new game is started, and only for those first few seconds.  Thereafter, the effect slowly becomes more and more banded, then more and more white, and stays that way, even across levels.

This is with your new scaling patch, but before your latest round patch, with bloom off, after starting a game and then _immediately_ cheating myself a rocket launcher and invincibility:

ElectricSheepOne_0000

**Comment by TrajansRow** [comment]
Excellent! This is really helpful information! My guess is that the increasing time value is creating large numbers that some GPUs don’t want to deal with. It might be an easy fix, but I will need to think about it...

**Comment by Hopper262** [comment]
Would you mind giving this one a try, Lia? I think this is the easiest fix if the time value is indeed the culprit. I'm not sure it'll help, but we may as well start simple and work our way up.

[Shader time test.zip](https://github.com/Aleph-One-Marathon/alephone/files/3004895/Shader.time.test.zip)

**Comment by ravenshining** [comment]
Gladly!  Doing these sorts of tests for you is a lot of fun :-)

With bloom disabled, it's working perfectly now, and doesn't break down over time:
starwars_0003

With bloom enabled, it's got a weird pattern to it right from the get-go, but it's not a bad one, it doesn't get worse over time, and it sort of shimmies up and down rather than slowly crawling downwards.  I'd call this an acceptable level of weird:

starwars_0004

**Comment by Hopper262** [comment]
Thanks! Sounds like it's working normally. The bloom column divisions slide to the left, but the colors in each column are random without a movement pattern I'm able to see.

What that test shader is doing is just replaying the first 2 seconds of static on a loop. By immediately dividing the large time value into a smaller number, it avoids the large multiplications your GPU didn't like. That limitation would cause problems for some animation styles (you'd notice the loop if those bloom bars did slowly crawl), but for a busy random pattern or a simple animation, it's OK.

Just for fun, I made a very different bloom, with a distinct animation pattern (a solid white shine moving upward). This should also work for you if I understand the problem correctly.

[Alternate static bloom.zip](https://github.com/Aleph-One-Marathon/alephone/files/3008916/Alternate.static.bloom.zip)

**Comment by ravenshining** [comment]
Ah, so are you taking the sine of game.ticks or something?  Running some further tests full-screen using this map and a timer, it takes about four seconds before it starts acting weird.

[static.sceA.zip](https://github.com/Aleph-One-Marathon/alephone/files/3010729/static.sceA.zip)

This other bloom also works, although it's not as good an effect I think.  For one it doesn't play well with the alien weapon:

WideningGyre_0008
vs.
WideningGyre_0002

It also looks bad on a wall.

**Comment by TrajansRow** [comment]
I made a variant of @Hopper262 's time test, only one that loops every five minutes or so, and has the changes recommended by @treellama. How does this work for you, @ravenshining ?
[Shader time fraction.zip](https://github.com/Aleph-One-Marathon/alephone/files/3011283/Shader.time.fraction.zip)

**Comment by ravenshining** [comment]
That's looking the best yet ;-)

I thought it was rather odd how the muzzzle flames of the alien weapon are ghosted in the above screenshots - then I noticed, they're entirely invisible when not invincible!  Then they reappear when bloom is disabled.  No other weapon seems to be affected!

Here's a shot with your latest plugin:

starwars_0000

**Pull request merged**
